### ISSUE TITLE
autobuild

### ISSUE THREAD

**Issue by antonmarin** [herloct/docker-phpmetrics#3]
could you setup autobuild container? latest version is 2.3.2, but container only for 2.2 ((

**Comment by herloct** [comment]
@antonmarin i'm sorry for the late reply, i've been busy lately and rarely touching PHP.

You could use @21ur1st's fork for more updated version [here](https://hub.docker.com/r/2ur1st/phpmetrics/)

PHPMetrics already has `Dockerfile` on their repositories too, but i can't find where they put the image, i don't know which are the official one in Docker Hub
